
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  
  <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
  
  <title>14.9 捕获异常后抛出另外的异常 — python3-cookbook 3.0.0 文档</title>
  

  
  
  
  

  

  
  
    

  

  <link href="https://python3-cookbook.readthedocs.io/zh_CN/latest/_static/css/theme.css" rel="stylesheet" type="text/css"/>
  <link href="https://python3-cookbook.readthedocs.io/zh_CN/latest/_static/pygments.css" rel="stylesheet" type="text/css"/>
    <link href="https://python3-cookbook.readthedocs.io/zh_CN/latest/genindex.html" rel="index" title="索引"/><script>
READTHEDOCS_DATA['page'] = 'c02/p02_match_text_at_start_end'
READTHEDOCS_DATA['source_suffix'] = '.rst'
</script>
    <link href="https://python3-cookbook.readthedocs.io/zh_CN/latest/search.html" rel="search" title="搜索"/>
    <link href="https://python3-cookbook.readthedocs.io/zh_CN/latest/copyright.html" rel="copyright" title="版权所有"/>
    
     

  
  


<!-- RTD Extra Head -->

<!-- 
Always link to the latest version, as canonical.
http://docs.readthedocs.org/en/latest/canonical.html
-->
<link href="https://python3-cookbook.readthedocs.io/zh_CN/latest/copyright.html" rel="canonical"/>

<link href="https://python3-cookbook.readthedocs.io/zh_CN/latest/copyright.html" rel="stylesheet" type="text/css"/>



<!-- Add page-specific data, which must exist in the page js, not global -->




<!-- end RTD <extrahead> -->
</head>
    <body>
    <div class="document" itemscope="itemscope" itemtype="http://schema.org/Article" role="main">
           <div itemprop="articleBody">
            
  <div class="section" id="id1">
<h1>14.9 捕获异常后抛出另外的异常<a class="headerlink" href="#id1" title="永久链接至标题">¶</a></h1>
<div class="section" id="id2">
<h2>问题<a class="headerlink" href="#id2" title="永久链接至标题">¶</a></h2>
<p>你想捕获一个异常后抛出另外一个不同的异常，同时还得在异常回溯中保留两个异常的信息。</p>
</div>
<div class="section" id="id3">
<h2>解决方案<a class="headerlink" href="#id3" title="永久链接至标题">¶</a></h2>
<p>为了链接异常，使用 <code class="docutils literal notranslate"><span class="pre">raise</span> <span class="pre">from</span></code> 语句来代替简单的 <code class="docutils literal notranslate"><span class="pre">raise</span></code> 语句。
它会让你同时保留两个异常的信息。例如：</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="gp">&gt;&gt;&gt; </span><span class="k">def</span> <span class="nf">example</span><span class="p">():</span>
<span class="gp">... </span>    <span class="k">try</span><span class="p">:</span>
<span class="gp">... </span>            <span class="nb">int</span><span class="p">(</span><span class="s1">'N/A'</span><span class="p">)</span>
<span class="gp">... </span>    <span class="k">except</span> <span class="ne">ValueError</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
<span class="gp">... </span>            <span class="k">raise</span> <span class="ne">RuntimeError</span><span class="p">(</span><span class="s1">'A parsing error occurred'</span><span class="p">)</span> <span class="kn">from</span> <span class="nn">e</span>
<span class="gp">...</span>
<span class="gp">&gt;&gt;&gt; </span><span class="n">example</span><span class="p">()</span>
<span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">"&lt;stdin&gt;"</span>, line <span class="m">3</span>, in <span class="n">example</span>
<span class="gr">ValueError</span>: <span class="n">invalid literal for int() with base 10: 'N/A'</span>
</pre></div>
</div>
<p>上面的异常是下面的异常产生的直接原因：</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="n">Traceback</span> <span class="p">(</span><span class="n">most</span> <span class="n">recent</span> <span class="n">call</span> <span class="n">last</span><span class="p">):</span>
  <span class="n">File</span> <span class="s2">"&lt;stdin&gt;"</span><span class="p">,</span> <span class="n">line</span> <span class="mi">1</span><span class="p">,</span> <span class="ow">in</span> <span class="o">&lt;</span><span class="n">module</span><span class="o">&gt;</span>
  <span class="n">File</span> <span class="s2">"&lt;stdin&gt;"</span><span class="p">,</span> <span class="n">line</span> <span class="mi">5</span><span class="p">,</span> <span class="ow">in</span> <span class="n">example</span>
<span class="ne">RuntimeError</span><span class="p">:</span> <span class="n">A</span> <span class="n">parsing</span> <span class="n">error</span> <span class="n">occurred</span>
<span class="o">&gt;&gt;&gt;</span>
</pre></div>
</div>
<p>在回溯中可以看到，两个异常都被捕获。
要想捕获这样的异常，你可以使用一个简单的 <code class="docutils literal notranslate"><span class="pre">except</span></code> 语句。
不过，你还可以通过查看异常对象的 <code class="docutils literal notranslate"><span class="pre">__cause__</span></code> 属性来跟踪异常链。例如：</p>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span><span class="k">try</span><span class="p">:</span>
    <span class="n">example</span><span class="p">()</span>
<span class="k">except</span> <span class="ne">RuntimeError</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
    <span class="k">print</span><span class="p">(</span><span class="s2">"It didn't work:"</span><span class="p">,</span> <span class="n">e</span><span class="p">)</span>

    <span class="k">if</span> <span class="n">e</span><span class="o">.</span><span class="n">__cause__</span><span class="p">:</span>
        <span class="k">print</span><span class="p">(</span><span class="s1">'Cause:'</span><span class="p">,</span> <span class="n">e</span><span class="o">.</span><span class="n">__cause__</span><span class="p">)</span>
</pre></div>
</div>
<p>当在 <code class="docutils literal notranslate"><span class="pre">except</span></code> 块中又有另外的异常被抛出时会导致一个隐藏的异常链的出现。例如：</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="gp">&gt;&gt;&gt; </span><span class="k">def</span> <span class="nf">example2</span><span class="p">():</span>
<span class="gp">... </span>    <span class="k">try</span><span class="p">:</span>
<span class="gp">... </span>            <span class="nb">int</span><span class="p">(</span><span class="s1">'N/A'</span><span class="p">)</span>
<span class="gp">... </span>    <span class="k">except</span> <span class="ne">ValueError</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
<span class="gp">... </span>            <span class="nb">print</span><span class="p">(</span><span class="s2">"Couldn't parse:"</span><span class="p">,</span> <span class="n">err</span><span class="p">)</span>
<span class="gp">...</span>
<span class="go">&gt;&gt;&gt;</span>
<span class="gp">&gt;&gt;&gt; </span><span class="n">example2</span><span class="p">()</span>
<span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">"&lt;stdin&gt;"</span>, line <span class="m">3</span>, in <span class="n">example2</span>
<span class="gr">ValueError</span>: <span class="n">invalid literal for int() with base 10: 'N/A'</span>
</pre></div>
</div>
<p>在处理上述异常的时候，另外一个异常发生了：</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="n">Traceback</span> <span class="p">(</span><span class="n">most</span> <span class="n">recent</span> <span class="n">call</span> <span class="n">last</span><span class="p">):</span>
  <span class="n">File</span> <span class="s2">"&lt;stdin&gt;"</span><span class="p">,</span> <span class="n">line</span> <span class="mi">1</span><span class="p">,</span> <span class="ow">in</span> <span class="o">&lt;</span><span class="n">module</span><span class="o">&gt;</span>
  <span class="n">File</span> <span class="s2">"&lt;stdin&gt;"</span><span class="p">,</span> <span class="n">line</span> <span class="mi">5</span><span class="p">,</span> <span class="ow">in</span> <span class="n">example2</span>
<span class="ne">NameError</span><span class="p">:</span> <span class="k">global</span> <span class="n">name</span> <span class="s1">'err'</span> <span class="ow">is</span> <span class="ow">not</span> <span class="n">defined</span>
<span class="o">&gt;&gt;&gt;</span>
</pre></div>
</div>
<p>这个例子中，你同时获得了两个异常的信息，但是对异常的解释不同。
这时候，<code class="docutils literal notranslate"><span class="pre">NameError</span></code> 异常被作为程序最终异常被抛出，而不是位于解析异常的直接回应中。</p>
<p>如果，你想忽略掉异常链，可使用 <code class="docutils literal notranslate"><span class="pre">raise</span> <span class="pre">from</span> <span class="pre">None</span></code> :</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="gp">&gt;&gt;&gt; </span><span class="k">def</span> <span class="nf">example3</span><span class="p">():</span>
<span class="gp">... </span>    <span class="k">try</span><span class="p">:</span>
<span class="gp">... </span>            <span class="nb">int</span><span class="p">(</span><span class="s1">'N/A'</span><span class="p">)</span>
<span class="gp">... </span>    <span class="k">except</span> <span class="ne">ValueError</span><span class="p">:</span>
<span class="gp">... </span>            <span class="k">raise</span> <span class="ne">RuntimeError</span><span class="p">(</span><span class="s1">'A parsing error occurred'</span><span class="p">)</span> <span class="kn">from</span> <span class="nn">None</span>
<span class="gp">...</span>
<span class="go">&gt;&gt;&gt;</span>
<span class="go">example3()</span>
<span class="gt">Traceback (most recent call last):</span>
  File <span class="nb">"&lt;stdin&gt;"</span>, line <span class="m">1</span>, in <span class="n">&lt;module&gt;</span>
  File <span class="nb">"&lt;stdin&gt;"</span>, line <span class="m">5</span>, in <span class="n">example3</span>
<span class="gr">RuntimeError</span>: <span class="n">A parsing error occurred</span>
<span class="go">&gt;&gt;&gt;</span>
</pre></div>
</div>
</div>
<div class="section" id="id4">
<h2>讨论<a class="headerlink" href="#id4" title="永久链接至标题">¶</a></h2>
<p>在设计代码时，在另外一个 <code class="docutils literal notranslate"><span class="pre">except</span></code> 代码块中使用 <code class="docutils literal notranslate"><span class="pre">raise</span></code> 语句的时候你要特别小心了。
大多数情况下，这种 <code class="docutils literal notranslate"><span class="pre">raise</span></code> 语句都应该被改成 <code class="docutils literal notranslate"><span class="pre">raise</span> <span class="pre">from</span></code> 语句。也就是说你应该使用下面这种形式：</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="k">try</span><span class="p">:</span>
   <span class="o">...</span>
<span class="k">except</span> <span class="n">SomeException</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
   <span class="k">raise</span> <span class="n">DifferentException</span><span class="p">()</span> <span class="kn">from</span> <span class="nn">e</span>
</pre></div>
</div>
<p>这样做的原因是你应该显示的将原因链接起来。
也就是说，<code class="docutils literal notranslate"><span class="pre">DifferentException</span></code> 是直接从 <code class="docutils literal notranslate"><span class="pre">SomeException</span></code> 衍生而来。
这种关系可以从回溯结果中看出来。</p>
<p>如果你像下面这样写代码，你仍然会得到一个链接异常，
不过这个并没有很清晰的说明这个异常链到底是内部异常还是某个未知的编程错误。</p>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span><span class="k">try</span><span class="p">:</span>
   <span class="o">...</span>
<span class="k">except</span> <span class="n">SomeException</span><span class="p">:</span>
   <span class="k">raise</span> <span class="n">DifferentException</span><span class="p">()</span>
</pre></div>
</div>
<p>当你使用 <code class="docutils literal notranslate"><span class="pre">raise</span> <span class="pre">from</span></code> 语句的话，就很清楚的表明抛出的是第二个异常。</p>
<p>最后一个例子中隐藏异常链信息。
尽管隐藏异常链信息不利于回溯，同时它也丢失了很多有用的调试信息。
不过万事皆平等，有时候只保留适当的信息也是很有用的。</p>
</div>
</div>


           </div>
           
          </div>
    </body>
</html>